### ISSUE TITLE
Add commit / version info to namelist or auxiliary file.

### ISSUE THREAD

**Issue by jklenzing** [jklenzing/sami2py#69]
The current commit and / or version info should be archived when a run is initiated.  This might work as a modification to the namelist file, or as a separate txt file.

**Comment by JonathonMSmith** [comment]
is this something that could be included in the logging issue #55?

**Comment by jklenzing** [comment]
I think that in the log term long term this info will be stored as part of the metadata in the netCDF output.  I'm not sure yet where the log info will go.

**Comment by jklenzing** [comment]
The log file isn’t necessarily output. I was thinking largely that a user could just change settings to send terminal output to a file.

**Comment by jklenzing** [comment]
Closing with merge of #75.
